GET http://localhost:5000/usuarios?usuario=edi
Accept: application/json

###
POST http://localhost:5000/usuarios
Content-Type: application/json

{
  "nome" : "Sidnei        ",
  "nick" : "sidnei",
  "email" : "sidnei@gmail.com",
  "senha" : "912343212222"
}

###
###Atualizando um Usuario
PUT http://localhost:5000/usuarios/1
Accept: application/json

###Inserindo um Usuário
POST http://localhost:5000/usuarios
Content-Type: application/json

###Buscando todos os Usuários
GET http://localhost:5000/usuarios
Accept: application/json

###Buscando Um Usuário
GET http://localhost:5000/usuarios/1
Accept: application/json

###


