### descurtir uma publicacao
POST http://{{url}}/publicacoes/1/descurtir
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzE2OTM4NjMsInVzdWFyaW9JZCI6M30.-sR5FJ91vv_RLU2KXEBV2XcnayTD8ObWaxCoWl3Dn_w

### Curtir uma Publicacao
POST http://{{url}}/publicacoes/1/curtir
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzE2OTM4NjMsInVzdWFyaW9JZCI6M30.-sR5FJ91vv_RLU2KXEBV2XcnayTD8ObWaxCoWl3Dn_w

### Retorna todas as publicacoes de um usuario específico
GET http://{{url}}/usuarios/1/publicacoes
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzE2OTA5NDksInVzdWFyaW9JZCI6M30.u3-OBO61r2Hw6Y-0u3dnzhIxVq6PLWwZkTRj0qVsi0o

### Remove uma publicacao do usuario
DELETE http://{{url}}/publicacoes/2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzE2OTA5NDksInVzdWFyaW9JZCI6M30.u3-OBO61r2Hw6Y-0u3dnzhIxVq6PLWwZkTRj0qVsi0o

### Atualizar uma Publicacao
PUT http://{{url}}/publicacoes/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzE2OTA5NDksInVzdWFyaW9JZCI6M30.u3-OBO61r2Hw6Y-0u3dnzhIxVq6PLWwZkTRj0qVsi0o

{
  "titulo" : "Titulo Novo Pra Ela",
  "conteudo" : "Conteudo Novo....."
}

### Retorna Todas as Publicacoes do usuario e de seus Seguidores, o parâmetro é pego do usuario no token
GET http://{{url}}/publicacoes
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzE2ODgyOTIsInVzdWFyaW9JZCI6Mn0.4NXQHMHWO2kuVM5SLSMrFH_OtohhbPGqmv2rgkh85GM

### Buscar uma publicacao Especifica
GET http://{{url}}/publicacoes/3
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzE2ODgyOTIsInVzdWFyaW9JZCI6Mn0.4NXQHMHWO2kuVM5SLSMrFH_OtohhbPGqmv2rgkh85GM

### Realiza uma Publicacao
POST http://{{url}}/publicacoes
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzE1Mjc3MTUsInVzdWFyaW9JZCI6Mn0.ynbEJqpmeuoyhd9qBxJJx1q3-3V4N2jng5NAlm9Ri2E

{
  "titulo" : "Minha Quarta Publicacao",
  "conteudo": "Hello World! 4"
}

### Gerar Token de um usuario
POST http://{{url}}/login
Content-Type: application/json

{
  "email" : "usuario3@gmail.com",
  "senha" : "123456"
}

### listar todos usuarios
GET http://{{url}}/usuarios
Accept: application/json

### Delete users
DELETE http://{{url}}/usuarios/1
Accept: application/json

### Atualizando um Usuario
PUT http://{{url}}/usuarios/7
Content-Type: application/json

{
  "nome" : "Nerli",
  "nick" : "nena",
  "email" : "nerli47@hotmail.com"
}

###Buscando um Usuario por ID
GET http://{{url}}/usuarios/2
Accept: application/json

### Busca com Parâmetros nome ou Nick
GET http://{{url}}/usuarios?usuario=edi
Accept: application/json

### Criando um Novo Usuario
POST http://{{url}}/usuarios
Content-Type: application/json

{
  "nome" : "Valoir        ",
  "nick" : "vmcod3r",
  "email" : "valoirmoura@gmail.com",
  "senha" : "teste12345"
}

### Atualizando um Usuario
PUT http://{{url}}/usuarios/1
Accept: application/json

###Inserindo um Usuário
POST http://{{url}}/usuarios
Content-Type: application/json

###Buscando todos os Usuários
GET http://{{url}}/usuarios
Accept: application/json

###Buscando Um Usuário
GET http://{{url}}/usuarios/1
Accept: application/json


